### PR TITLE
Sync LLVM 3.7.1 patches

### PR DESCRIPTION
**Pull request by yuyichao**
This is basically blindly copying the first commit in https://github.com/staticfloat/homebrew-julia/pull/205 not sure what else needs to be done.

@tkelman @staticfloat

### CODE REVIEW

**Comment by staticfloat** [comment]
Thanks @yuyichao!  I was wondering why julia `HEAD` wasn't building anymore.  :)

**Comment by staticfloat** [comment]
Hmmm.  [Build failure on OSX 10.11](https://build.julialang.org/builders/bottle_osx10.11-x64/builds/36/steps/shell/logs/stdio).

**Comment by yuyichao** [comment]
@staticfloat  Do you mean there's a build failure before this? The patch here should be only performance fixes and shouldn't affect the build.

**Comment by tkelman** [comment]
You need to bottle this right away to avoid making Julia's OSX Travis try to build from source and time out. I'm reverting this - reopen it against the staging branch.

**Comment by yuyichao** [comment]
I have no idea what to do here (or even if there's anything I need to do here) so I'll assume one of you will take care of it.

**Comment by tkelman** [comment]
@staticfloat updated the staging branch https://github.com/staticfloat/homebrew-julia/tree/staging to match the state of master after this was merged. Hopefully master should allow Julia OSX Travis builds to go through again, and once @staticfloat gets new bottles built we can merge them from staging into master to avoid another interruption in binary availability.

Only action required from you is to open the next one of these against staging instead of master.

**Comment by yuyichao** [comment]
> Only action required from you is to open the next one of these against staging instead of master.

Got it

**Comment by staticfloat** [comment]
Yeah, sorry Tony, I thought it would go right through, and then when it errored out, I didn't think to revert `master`.

@yuyichao There seems to be an error when building `libcxx` on 10.11.  The relevant part is:
```
==> make -C /private/tmp/llvm37-julia-20160609-13985-f0hf2v/llvm-3.7.1.src/projects/libcxx install CC=/usr/local/Cellar/llvm37-julia/3.7.1_1/lib/llvm-3.7.1/bin/clang CXX=/usr/local/Cellar/llvm37-julia/3.7.1_1/lib/llvm-3.7.1/bin/clang++ MACOSX_DEPLOYMENT_TARGET=10.11 DSTROOT=/usr/local/Cellar/llvm37-julia/3.7.1_1/lib/llvm-3.7.1 SYMROOT=/private/tmp/llvm37-julia-20160609-13985-f0hf2v/llvm-3.7.1.src/projects/libcxx
cd lib && ./buildit
+ for FILE in '../src/*.cpp'
+ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -g -Os -arch i386 -arch x86_64 -nostdinc++ -std=c++11 -fstrict-aliasing -Wall -Wextra -Wshadow -Wconversion -Wpadded -Wstrict-aliasing=2 -Wstrict-overflow=4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I../include ../src/algorithm.cpp
In file included from ../src/algorithm.cpp:11:
In file included from ../include/random:1645:
../include/string:1938:44: error: 'basic_string<_CharT, _Traits, _Allocator>' is missing exception specification 'noexcept(is_nothrow_copy_constructible<allocator_type>::value)'
basic_string<_CharT, _Traits, _Allocator>::basic_string(const allocator_type& __a)
                                           ^
../include/string:1326:40: note: previous declaration is here
    _LIBCPP_INLINE_VISIBILITY explicit basic_string(const allocator_type& __a)
                                       ^
1 error generated.
make: *** [install] Error 1
```

**Comment by yuyichao** [comment]
> There seems to be an error when building libcxx on 10.11

Sorry I have no idea what that could be. You'll probably have more luck asking someone that actually uses OSX...

**Comment by staticfloat** [comment]
It's worth pointing out that the `homebrew/versions/llvm37` formula has the same problem on 10.11.

**Comment by tkelman** [comment]
could we skip libcxx? I think Keno initially copied this formula from versions

**Comment by staticfloat** [comment]
[Homebrew/versions issue](https://github.com/Homebrew/homebrew-versions/issues/1298)

**Pull request merged**
