### PR TITLE
new llvm 3.7.1 patch

### PR DESCRIPTION
**Pull request by tkelman**
cc @staticfloat is this right to set up a new revision? pr against staging

### CODE REVIEW

**Comment by tkelman** [comment]
Oh, and I think we should probably build bottles with assertions enabled

**Comment by staticfloat** [comment]
This is correct, great job.

**Comment by staticfloat** [comment]
Do you want to include assertions in non-debug builds?  I thought we didn't include them due to slowdowns.

**Comment by tkelman** [comment]
I build the appveyor binaries with assertions, I don't think the perf difference is all that big

**Comment by staticfloat** [comment]
Do we need to explicitly enable assertions?  Because it looks to me like they're already enabled. It looks like we would have to [explicitly include `--disable-assertions`](https://github.com/tkelman/homebrew-julia/blob/patch-1/llvm37-julia.rb#L199) for this formula to disable them in any case.

**Comment by tkelman** [comment]
Not sure. Would probably have to check llvm's configure to see what it does without a flag specified one way or the other

**Comment by tkelman** [comment]
Defaults to yes according to `./configure --help` so I guess we're good

**Comment by staticfloat** [comment]
Then let the building commence!

**Comment by tkelman** [comment]
http://m.youtube.com/watch?v=-YCN-a0NsNk

**Pull request merged**
