### PR TITLE
is this how homebrew works?

### PR DESCRIPTION
**Pull request by tkelman**
try disabling assertions by default on llvm37-julia

cc @Keno and @staticfloat ~~I'm trying to click the right buttons on the buildbot but homebrew is unhappy? https://build.julialang.org/builders/bottle_osx10.10-x64/builds/2/steps/shell/logs/stdio~~ my bad

### CODE REVIEW

**Comment by tkelman** [comment]
looks like this may have worked
when https://build.julialang.org/builders/bottle_osx10.9-x64/builds/2 and https://build.julialang.org/builders/bottle_osx10.10-x64/builds/3 and https://build.julialang.org/builders/bottle_osx10.11-x64/builds/3 finish successfully then we paste in the sha's and merge, I think

**Comment by staticfloat** [comment]
I think you need to change [this line as well](https://github.com/staticfloat/homebrew-julia/blob/72d1fd22d56c4141961b8f2209337adaaf289adb/llvm37-julia.rb#L199).  Something like:
```
args << "--disable-assertions" if not build.with? "assertions"
```

**Comment by tkelman** [comment]
doesn't homebrew do the antonyms automatically?
```
==> /private/tmp/llvm37-julia20160113-87343-y1h5q6/llvm-3.7.1.src/configure --prefix=/usr/local/Cellar/llvm37-julia/3.7.1_1/lib/llvm-3.7.1 --enable-optimized --disable-bindings --with-gmp=/usr/local/opt/gmp --enable-targets=host --enable-shared --disable-assertions --enable-libffi
```

**Comment by staticfloat** [comment]
Wow, I had no idea.  Amazing.

**Comment by tkelman** [comment]
shall we try these?

**Comment by staticfloat** [comment]
Roger roger.

**Pull request merged**
