### PR TITLE
Add LLVM 3.7.1 Formula

### PR DESCRIPTION
**Pull request by Keno**
I didn't switch over julia yet, because I didn't know the incantations to make sure that 0.4 continues to use 3.3, but I did test that this builds ok.

### CODE REVIEW

**Comment by Keno** [comment]
cc @tkelman

**Comment by tkelman** [comment]
Cool. I think there's a way we can use a url to the copies of the patch files from the julia repo instead of pasting the content here?

**Comment by Keno** [comment]
No idea, I just clean here.

**Comment by tkelman** [comment]
:grinning: 

ping @staticfloat if your notifications aren't on here. Is https://github.com/staticfloat/homebrew-julia/blob/3f768c6a18423a7c6323e9f95c8f81cb48585bff/julia.rb#L56-L69 the basic patch-file-url syntax?

**Comment by staticfloat** [comment]
Yep, define a `patches` method and return a list of urls to have them downloaded and applied.  I'll build this and ensure it works with `julia`.

**Comment by Keno** [comment]
Ok, done.

**Comment by staticfloat** [comment]
Time to try bottling.

**Comment by tkelman** [comment]
Looks like the bottling jobs succeeded?

**Comment by staticfloat** [comment]
Looks like.  Let's try it.  I've pushed the changes to the `staging` branch, and I have [a branch of Julia](https://travis-ci.org/JuliaLang/julia/jobs/100777687) testing these changes out on Travis right now.

**Pull request merged**
