### PR TITLE
Fixes for bottles due to release of GCC 5

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@tkelman those failures involving `libgfortran` on Homebrew-powered Julia builds should be fixed now.

**Comment by tkelman** [comment]
Good to know, thanks - and I thought we went to a bunch of trouble to avoid this problem, but I guess it'll still happen at major version bumps? Which will now be much more common. Argh.

**Comment by staticfloat** [comment]
I'm pretty sure it's the `X` that matters, as opposed to the `Y` in `X.Y`.  Hopefully `X` won't change too often.

**Comment by tkelman** [comment]
No, part of the reason they decided to go from 4.9 to 5.x (5.0 during development, release tagged as 5.1) was because the major digit had lost meaning and they plan on bumping the major more often now - https://gcc.gnu.org/develop.html, the development branch for gcc is already "gcc 6 stage 1"

**Comment by staticfloat** [comment]
Oh, wow.  I see.  Well, half of the problem from before was due to the `Z` in `X.Y.Z`, which was due to OS updates and whatnot.  I think we'll be able to survive the OS updates, but it is a little annoying.  It can't really be helped though.

**Comment by tkelman** [comment]
It would also be nice if homebrew were as smart as real package managers about versioning...

**Comment by staticfloat** [comment]
Even if I were using `deb`'s on Linux, if `libgcc` ups its major version number, I have to re-link.  That's the whole point of major version numbers, right?  The problem is that since OSX doesn't enforce SO versions, in order for Homebrew to play nicely with as many software packages as possible, they treat the major version number of the software as always constituting an API breakage.

**Comment by tkelman** [comment]
Right but generally deb's don't force you to upgrade the version of libgcc you're linking to until you choose to rebuild against the new one, not immediately as soon as the gcc maintainer chooses to bump his version, yeah?

**Comment by staticfloat** [comment]
Oh, I see what you mean.   Homebrew doesn't force you to upgrade, but it doesn't allow you to install old versions very easily.  The reason we run into this so often is because we have so many clean installs (travis, etc...)

**Comment by tkelman** [comment]
Existing systems may continue to work with previously-working combinations of packages, but forced breakage of your reverse-deps is... suboptimal.

**Pull request merged**
