### PR TITLE
fix patching with stable

### PR DESCRIPTION
**Pull request by ZacCranko**
This pr addresses #163 But I haven't been able to get stable and HEAD installed with the usual `brew unlink` trick.

### CODE REVIEW

**Comment by staticfloat** [comment]
Ah, shoot.  Thanks @ZacCranko for this quick fix.  Can you explain in greater detail what problems you're having with `unlink`?

**Comment by ZacCranko** [comment]
I used to be able to `brew install julia && brew unlink julia && brew install julia --HEAD` and have both head and stable installed. But for some reason when I try to do this now when i try to `brew install julia --HEAD`, homebrew complains that julia is already installed. 

Not sure though if this is a product of switching to El Capitan or more recent changes with `homebrew-julia`.

**Comment by staticfloat** [comment]
Can you post the exact error message?

**Comment by ZacCranko** [comment]
After running `brew install julia && brew unlink julia && brew install --HEAD` it outputs

```
Unlinking /usr/local/Cellar/julia/0.3.10... 13 symlinks removed
Warning: staticfloat/julia/julia-0.3.10 already installed, it's just not linked
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Pull request merged**
