### PR TITLE
Libgfortran 6.1 dance

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by tkelman** [comment]
do ipopt and the like in juliadeps also need rebuilding?

**Comment by jenshnielsen** [comment]
Since this only bumps the revision on the arpack bottle not the package it self I had to manually reinstall that package to get tests passing. The old one is linked against the old openblas. The same may be true for suite-sparse
```
Exception running test linalg/arnoldi :
On worker 4:
LoadError: error compiling naupd: could not load library "libarpack"
dlopen(libarpack.dylib, 1): Library not loaded: /usr/local/opt/openblas-julia/lib/libopenblasp-r0.2.17.dylib
  Referenced from: /usr/local/opt/arpack-julia/lib/libarpack.dylib
  Reason: image not found
 in aupd_wrapper at linalg/arpack.jl:49
 in _eigs at linalg/arnoldi.jl:228
 in eigs at linalg/arnoldi.jl:51
 in eigs at linalg/arnoldi.jl:50
 in anonymous at /usr/local/Cellar/julia/0.4.5_1/share/julia/test/linalg/arnoldi.jl:35
 in include_string at loading.jl:282
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 [inlined code] from util.jl:179
 in runtests at /usr/local/Cellar/julia/0.4.5_1/share/julia/test/testdefs.jl:7
 in anonymous at /usr/local/Cellar/julia/0.4.5_1/share/julia/test/runtests.jl:36
 in anonymous at multi.jl:923
 in run_work_thunk at multi.jl:661
 [inlined code] from multi.jl:923
 in anonymous at task.jl:63
while loading /usr/local/Cellar/julia/0.4.5_1/share/julia/test/linalg/arnoldi.jl, in expression starting on line 8
ERROR: LoadError: Some tests exited with errors.
 in anonymous at /usr/local/Cellar/julia/0.4.5_1/share/julia/test/runtests.jl:64
 in cd at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
while loading /usr/local/Cellar/julia/0.4.5_1/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in runtests at interactiveutil.jl:411
 in runtests at interactiveutil.jl:400
 in process_options at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
```

**Comment by staticfloat** [comment]
Thanks @jenshnielsen, I knew there was a reason not to just use bottle revisions.  I've updated the bottles now, so this shouldn't affect users anymore.

**Comment by tkelman** [comment]
what's the difference between formula revisions and bottle revisions? other than the latter causes issues for us?

**Comment by staticfloat** [comment]
A Formula revision is used to denote something changed in the formula itself, and serves as a greater version when comparing installed vs. available versions on upgrade.  A bottle revision is used to denote that something changed in the bottling process itself, and doesn't get upgraded automatically.  In practice, we should always be using formula revisions when rebottling.

**Comment by jenshnielsen** [comment]
@staticfloat Thanks, works now. Your explanation matches my understanding too.

**Pull request merged**
