### PR TITLE
Change SHA1 sums to SHA256 sums for resources

### PR DESCRIPTION
**Pull request by tchajed**
Not exactly sure how to download the bottles for other versions of OS X to
compute their SHA256 sums, but happy to update the pull request if someone
explains how to figure out the bottle URLs.

### CODE REVIEW

**Comment by tchajed** [comment]
Oops, didn't realize this is essentially the same as #215. Updated to add SHA256 sums of bottles (the other pull request also makes some extraneous whitespace changes).

**Comment by tchajed** [comment]
Also this fixes #216.

**Comment by ellisvalentiner** [comment]
I recommend closing this in favor of https://github.com/staticfloat/homebrew-julia/pull/215.

Perhaps someone else can provide instructions on how to obtain the checksums for specific macOS builds.

**Comment by staticfloat** [comment]
Closing in favor of #215, thanks for your help regardless!

**Pull request closed without merging**
